//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_userorder()
        {
            this.tbl_productoordered = new HashSet<tbl_productoordered>();
        }
    
        public int or_id { get; set; }
        public string o_usename { get; set; }
        public string o_phone { get; set; }
        public string o_email { get; set; }
        public Nullable<System.DateTime> o_createon { get; set; }
        public Nullable<bool> o_approved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_productoordered> tbl_productoordered { get; set; }
    }
}
